# Generated by Django 3.0.1 on 2022-04-18 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=30)),
                ('describe', models.CharField(max_length=1000)),
                ('joindate', models.DateField(auto_now_add=True)),
                ('image_1', models.ImageField(upload_to='product image/')),
                ('image_2', models.ImageField(upload_to='product image/')),
                ('image_3', models.ImageField(upload_to='product image/')),
                ('garden', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=30)),
                ('total_quantity', models.IntegerField(verbose_name=5)),
                ('unit', models.CharField(max_length=20)),
                ('price', models.IntegerField(verbose_name=5)),
                ('price_per_quantity', models.CharField(max_length=20)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
