# Generated by Django 3.0.1 on 2022-05-02 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(max_length=5),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(max_length=5)),
                ('total_price', models.IntegerField(max_length=5)),
                ('address', models.CharField(max_length=500)),
                ('shipped', models.BooleanField(default=False)),
                ('delivered', models.BooleanField(default=False)),
                ('order', models.BooleanField(default=True)),
                ('payment', models.BooleanField(default=False)),
                ('order_on', models.DateField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Product')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Seller')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Visitor')),
            ],
        ),
    ]
